# KDE tags expanded automatically by am_edit - $Revision: 1.13 $ 
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



####### kdevelop will overwrite this part!!! (begin)##########

SHELL = /bin/bash

srcdir = .
top_srcdir = ../..

prefix = /usr/local/kde
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/share/info
mandir = ${prefix}/share/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/rars
pkglibdir = $(libdir)/rars
pkgincludedir = $(includedir)/rars
top_builddir = ../..

ACLOCAL = ${SHELL} /home/user/torcs/rars/admin/missing --run aclocal-1.11
AUTOCONF = ${SHELL} /home/user/torcs/rars/admin/missing --run autoconf
AUTOMAKE = ${SHELL} /home/user/torcs/rars/admin/missing --run automake-1.11
AUTOHEADER = ${SHELL} /home/user/torcs/rars/admin/missing --run autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = 
build_triplet = i686-pc-linux-gnu
host_alias = 
host_triplet = i686-pc-linux-gnu
target_alias = 
target_triplet = i686-pc-linux-gnu
AMTAR = ${SHELL} /home/user/torcs/rars/admin/missing --run tar
ARTSCCONFIG = 
AS = @AS@
AUTODIRS = 
AWK = gawk
CC = /usr/bin/gcc-4.1
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in
CPP = /usr/bin/gcc-4.1 -E
CXX = /usr/bin/g++-4.1
CXXCPP = /usr/bin/g++-4.1 -E
DCOPIDL = /usr/bin/dcopidl
DCOPIDL2CPP = /usr/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /usr/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/usr/include/kde
KDE_LDFLAGS = -L/usr/lib
KDE_MT_LDFLAGS = 
KDE_MT_LIBS = -lpthread
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = -R $(kde_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = /usr/share/apps/ksgmltools2/customization/kde-chunk.xsl
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBGEN = @LIBGEN@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = 
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = -lresolv
LIBSHADOW = @LIBSHADOW@
LIBSM = -lSM -lICE
LIBSOCKET =  -lresolv
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBUTIL = -lutil
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEPRINT = -lkdeprint
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkio
LIB_KFM = 
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lkio
LIB_QPE = 
LIB_QT = -lqt-mt  $(LIBPNG) -lXext $(LIB_X11) $(LIBSM) -lpthread
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LIB_XEXT = -lXext
LN_S = ln -s
MCOPIDL = 
MEINPROC = /usr/bin/meinproc
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CFLAGS = 
NOOPT_CXXFLAGS = 
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = rars
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTE_NORTTI = 
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = -I/usr/include/qt3
QT_LDFLAGS = 
RANLIB = ranlib
RC = @RC@
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  doc po rars
UIC = /usr/bin/uic -L $(kde_widgetdir) -nounload
UIC_TR = tr2i18n
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = 
USE_RTTI = 
USE_THREADS = 
VERSION = 0.90
WOVERLOADED_VIRTUAL = 
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS =  -lresolv
X_INCLUDES = -I.
X_LDFLAGS = -L/usr/lib
X_PRE_LIBS = 
all_includes = -I/usr/include/kde -I/usr/include/qt3 -I. 
all_libraries = -L/usr/lib 
am__include = include
am__quote = 
idldir = @idldir@
install_sh = ${SHELL} /home/user/torcs/rars/admin/install-sh
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /usr/include/kde
kde_libraries = /usr/lib
kde_libs_htmldir = /usr/share/doc/kde/HTML
kde_libs_prefix = /usr
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${libdir}/kde3
kde_qtver = 3
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_styledir = ${libdir}/kde3/plugins/styles
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
kde_widgetdir = ${libdir}/kde3/plugins/designer
micodir = @micodir@
qt_includes = /usr/include/qt3
qt_libraries = 
x_includes = .
x_libraries = /usr/lib

SUBDIRS = texture model 

EXTRA_DIST = aalborg.trk adelaide.trk albert.trk albrtprk.trk anew.trk austria.trk barcelon.trk brands.trk brazil.trk buenos.trk clkwis.trk cstlcomb.trk doningtn.trk zandvort.trk dreiw.trk elev2.trk estoril.trk figure8.trk fiorano.trk fourmile.trk hock.trk hungary.trk kevin.trk imola.trk indy500.trk indygp.trk jerez.trk kimla01.trk kimla02.trk kimla03.trk kimla04.trk kimla05.trk longrand.trk loudon.trk magnycrs.trk michigan.trk midohio.trk mlwaukee.trk monaco.trk montreal.trk nurnburg.trk phoenix.trk oval2.trk monza-55.trk monza-76.trk mosport.trk nazareth.trk per1.trk pocono.trk ra.trk ramdu.trk rars.trk s1.trk silver97.trk wierd.trk watglen.trk v03.trk v02.trk s2.trk v01.trk trouble.trk tremblnt.trk sepang.trk season silverst.trk spa.trk speed2.trk stef2.trk suzuka.trk timin.trk random.trk t_eight.trx t_zero.trx 
subdir = rars/tracks
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
DIST_SOURCES =

RECURSIVE_TARGETS = info-recursive dvi-recursive install-info-recursive \
	uninstall-info-recursive all-recursive install-data-recursive \
	install-exec-recursive installdirs-recursive install-recursive \
	uninstall-recursive check-recursive installcheck-recursive
DIST_COMMON = Makefile.am Makefile.in
DIST_SUBDIRS = $(SUBDIRS)
#>- all: all-recursive
#>+ 1
all: docs-am  all-recursive

.SUFFIXES:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
#>- 	cd $(top_srcdir) && \
#>- $(AUTOMAKE) --gnu  rars/tracks/Makefile
#>+ 3
	cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  rars/tracks/Makefile
	cd $(top_srcdir) && perl admin/am_edit rars/tracks/Makefile.in
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	CONFIG_HEADERS= CONFIG_LINKS= \
	CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
uninstall-info-am:

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	echo "Making $$target in $$subdir"; \
	if test "$$subdir" = "."; then \
	dot_seen=yes; \
	local_target="$$target-am"; \
	else \
	local_target="$$target"; \
	fi; \
	(cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	|| case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	$(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
	maintainer-clean-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	case "$@" in \
	distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	*) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	if test "$$subdir" = "."; then :; else \
	rev="$$subdir $$rev"; \
	fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	echo "Making $$target in $$subdir"; \
	if test "$$subdir" = "."; then \
	local_target="$$target-am"; \
	else \
	local_target="$$target"; \
	fi; \
	(cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	|| case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	done | \
	$(AWK) '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
	$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	if test "$$subdir" = .; then :; else \
	test -f $$subdir/TAGS && tags="$$tags -i $$here/$$subdir/TAGS"; \
	fi; \
	done; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	done | \
	$(AWK) '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	|| etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	&& cd $(top_srcdir) \
	&& gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

#>- DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=t_spa.trx 

DISTFILES= $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	if test -f $$file; then d=.; else d=$(srcdir); fi; \
	dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	$(mkinstalldirs) "$(distdir)/$$dir"; \
	fi; \
	if test -d $$d/$$file; then \
	cp -pR $$d/$$file $(distdir) \
	|| exit 1; \
	else \
	test -f $(distdir)/$$file \
	|| cp -p $$d/$$file $(distdir)/$$file \
	|| exit 1; \
	fi; \
	done
	for subdir in $(SUBDIRS); do \
	if test "$$subdir" = .; then :; else \
	test -d $(distdir)/$$subdir \
	|| mkdir $(distdir)/$$subdir \
	|| exit 1; \
	(cd $$subdir && \
	$(MAKE) $(AM_MAKEFLAGS) \
	top_distdir="$(top_distdir)" \
	distdir=../$(distdir)/$$subdir \
	distdir) \
	|| exit 1; \
	fi; \
	done
check-am: all-am
check: check-recursive
all-am: Makefile
installdirs: installdirs-recursive
installdirs-am:

install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	`test -z '$(STRIP)' || \
	echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#>- clean: clean-recursive
#>+ 1
clean: kde-rpo-clean  clean-recursive

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive

distclean-am: clean-am distclean-generic distclean-libtool \
	distclean-tags

dvi: dvi-recursive

dvi-am:

info: info-recursive

info-am:

install-data-am: install-data-local

install-exec-am:

install-info: install-info-recursive

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-recursive

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

uninstall-am: uninstall-info-am uninstall-local

uninstall-info: uninstall-info-recursive

.PHONY: $(RECURSIVE_TARGETS) GTAGS all all-am check check-am clean \
	clean-generic clean-libtool clean-recursive distclean \
	distclean-generic distclean-libtool distclean-recursive \
	distclean-tags distdir dvi dvi-am dvi-recursive info info-am \
	info-recursive install install-am install-data install-data-am \
	install-data-local install-data-recursive install-exec \
	install-exec-am install-exec-recursive install-info \
	install-info-am install-info-recursive install-man \
	install-recursive install-strip installcheck installcheck-am \
	installdirs installdirs-am installdirs-recursive \
	maintainer-clean maintainer-clean-generic \
	maintainer-clean-recursive mostlyclean mostlyclean-generic \
	mostlyclean-libtool mostlyclean-recursive tags tags-recursive \
	uninstall uninstall-am uninstall-info-am \
	uninstall-info-recursive uninstall-local uninstall-recursive


install-data-local:
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/aalborg.trk /usr/share/rars/tracks/aalborg.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/aalborg.trk $(DESTDIR)/usr/share/rars/tracks/aalborg.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/adelaide.trk /usr/share/rars/tracks/adelaide.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/adelaide.trk $(DESTDIR)/usr/share/rars/tracks/adelaide.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/albert.trk /usr/share/rars/tracks/albert.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/albert.trk $(DESTDIR)/usr/share/rars/tracks/albert.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/albrtprk.trk /usr/share/rars/tracks/albrtprk.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/albrtprk.trk $(DESTDIR)/usr/share/rars/tracks/albrtprk.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/anew.trk /usr/share/rars/tracks/anew.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/anew.trk $(DESTDIR)/usr/share/rars/tracks/anew.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/austria.trk /usr/share/rars/tracks/austria.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/austria.trk $(DESTDIR)/usr/share/rars/tracks/austria.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/barcelon.trk /usr/share/rars/tracks/barcelon.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/barcelon.trk $(DESTDIR)/usr/share/rars/tracks/barcelon.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/brands.trk /usr/share/rars/tracks/brands.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/brands.trk $(DESTDIR)/usr/share/rars/tracks/brands.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/brazil.trk /usr/share/rars/tracks/brazil.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/brazil.trk $(DESTDIR)/usr/share/rars/tracks/brazil.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/buenos.trk /usr/share/rars/tracks/buenos.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/buenos.trk $(DESTDIR)/usr/share/rars/tracks/buenos.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/clkwis.trk /usr/share/rars/tracks/clkwis.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/clkwis.trk $(DESTDIR)/usr/share/rars/tracks/clkwis.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/cstlcomb.trk /usr/share/rars/tracks/cstlcomb.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/cstlcomb.trk $(DESTDIR)/usr/share/rars/tracks/cstlcomb.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/doningtn.trk /usr/share/rars/tracks/doningtn.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/doningtn.trk $(DESTDIR)/usr/share/rars/tracks/doningtn.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/zandvort.trk /usr/share/rars/tracks/zandvort.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/zandvort.trk $(DESTDIR)/usr/share/rars/tracks/zandvort.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/dreiw.trk /usr/share/rars/tracks/dreiw.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/dreiw.trk $(DESTDIR)/usr/share/rars/tracks/dreiw.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/elev2.trk /usr/share/rars/tracks/elev2.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/elev2.trk $(DESTDIR)/usr/share/rars/tracks/elev2.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/estoril.trk /usr/share/rars/tracks/estoril.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/estoril.trk $(DESTDIR)/usr/share/rars/tracks/estoril.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/figure8.trk /usr/share/rars/tracks/figure8.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/figure8.trk $(DESTDIR)/usr/share/rars/tracks/figure8.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/fiorano.trk /usr/share/rars/tracks/fiorano.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/fiorano.trk $(DESTDIR)/usr/share/rars/tracks/fiorano.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/fourmile.trk /usr/share/rars/tracks/fourmile.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/fourmile.trk $(DESTDIR)/usr/share/rars/tracks/fourmile.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/hock.trk /usr/share/rars/tracks/hock.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/hock.trk $(DESTDIR)/usr/share/rars/tracks/hock.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/hungary.trk /usr/share/rars/tracks/hungary.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/hungary.trk $(DESTDIR)/usr/share/rars/tracks/hungary.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/kevin.trk /usr/share/rars/tracks/kevin.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kevin.trk $(DESTDIR)/usr/share/rars/tracks/kevin.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/imola.trk /usr/share/rars/tracks/imola.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/imola.trk $(DESTDIR)/usr/share/rars/tracks/imola.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/indy500.trk /usr/share/rars/tracks/indy500.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/indy500.trk $(DESTDIR)/usr/share/rars/tracks/indy500.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/indygp.trk /usr/share/rars/tracks/indygp.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/indygp.trk $(DESTDIR)/usr/share/rars/tracks/indygp.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/jerez.trk /usr/share/rars/tracks/jerez.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/jerez.trk $(DESTDIR)/usr/share/rars/tracks/jerez.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/kimla01.trk /usr/share/rars/tracks/kimla01.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kimla01.trk $(DESTDIR)/usr/share/rars/tracks/kimla01.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/kimla02.trk /usr/share/rars/tracks/kimla02.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kimla02.trk $(DESTDIR)/usr/share/rars/tracks/kimla02.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/kimla03.trk /usr/share/rars/tracks/kimla03.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kimla03.trk $(DESTDIR)/usr/share/rars/tracks/kimla03.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/kimla04.trk /usr/share/rars/tracks/kimla04.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kimla04.trk $(DESTDIR)/usr/share/rars/tracks/kimla04.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/kimla05.trk /usr/share/rars/tracks/kimla05.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/kimla05.trk $(DESTDIR)/usr/share/rars/tracks/kimla05.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/longrand.trk /usr/share/rars/tracks/longrand.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/longrand.trk $(DESTDIR)/usr/share/rars/tracks/longrand.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/loudon.trk /usr/share/rars/tracks/loudon.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/loudon.trk $(DESTDIR)/usr/share/rars/tracks/loudon.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/magnycrs.trk /usr/share/rars/tracks/magnycrs.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/magnycrs.trk $(DESTDIR)/usr/share/rars/tracks/magnycrs.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/michigan.trk /usr/share/rars/tracks/michigan.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/michigan.trk $(DESTDIR)/usr/share/rars/tracks/michigan.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/midohio.trk /usr/share/rars/tracks/midohio.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/midohio.trk $(DESTDIR)/usr/share/rars/tracks/midohio.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/mlwaukee.trk /usr/share/rars/tracks/mlwaukee.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/mlwaukee.trk $(DESTDIR)/usr/share/rars/tracks/mlwaukee.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/monaco.trk /usr/share/rars/tracks/monaco.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/monaco.trk $(DESTDIR)/usr/share/rars/tracks/monaco.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/montreal.trk /usr/share/rars/tracks/montreal.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/montreal.trk $(DESTDIR)/usr/share/rars/tracks/montreal.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/nurnburg.trk /usr/share/rars/tracks/nurnburg.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/nurnburg.trk $(DESTDIR)/usr/share/rars/tracks/nurnburg.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/phoenix.trk /usr/share/rars/tracks/phoenix.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/phoenix.trk $(DESTDIR)/usr/share/rars/tracks/phoenix.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/oval2.trk /usr/share/rars/tracks/oval2.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/oval2.trk $(DESTDIR)/usr/share/rars/tracks/oval2.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/monza-55.trk /usr/share/rars/tracks/monza-55.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/monza-55.trk $(DESTDIR)/usr/share/rars/tracks/monza-55.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/monza-76.trk /usr/share/rars/tracks/monza-76.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/monza-76.trk $(DESTDIR)/usr/share/rars/tracks/monza-76.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/mosport.trk /usr/share/rars/tracks/mosport.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/mosport.trk $(DESTDIR)/usr/share/rars/tracks/mosport.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/nazareth.trk /usr/share/rars/tracks/nazareth.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/nazareth.trk $(DESTDIR)/usr/share/rars/tracks/nazareth.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/per1.trk /usr/share/rars/tracks/per1.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/per1.trk $(DESTDIR)/usr/share/rars/tracks/per1.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/pocono.trk /usr/share/rars/tracks/pocono.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/pocono.trk $(DESTDIR)/usr/share/rars/tracks/pocono.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/ra.trk /usr/share/rars/tracks/ra.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/ra.trk $(DESTDIR)/usr/share/rars/tracks/ra.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/ramdu.trk /usr/share/rars/tracks/ramdu.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/ramdu.trk $(DESTDIR)/usr/share/rars/tracks/ramdu.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/rars.trk /usr/share/rars/tracks/rars.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/rars.trk $(DESTDIR)/usr/share/rars/tracks/rars.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/s1.trk /usr/share/rars/tracks/s1.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/s1.trk $(DESTDIR)/usr/share/rars/tracks/s1.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/silver97.trk /usr/share/rars/tracks/silver97.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/silver97.trk $(DESTDIR)/usr/share/rars/tracks/silver97.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/wierd.trk /usr/share/rars/tracks/wierd.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/wierd.trk $(DESTDIR)/usr/share/rars/tracks/wierd.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/watglen.trk /usr/share/rars/tracks/watglen.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/watglen.trk $(DESTDIR)/usr/share/rars/tracks/watglen.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/v03.trk /usr/share/rars/tracks/v03.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/v03.trk $(DESTDIR)/usr/share/rars/tracks/v03.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/v02.trk /usr/share/rars/tracks/v02.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/v02.trk $(DESTDIR)/usr/share/rars/tracks/v02.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/s2.trk /usr/share/rars/tracks/s2.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/s2.trk $(DESTDIR)/usr/share/rars/tracks/s2.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/v01.trk /usr/share/rars/tracks/v01.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/v01.trk $(DESTDIR)/usr/share/rars/tracks/v01.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/trouble.trk /usr/share/rars/tracks/trouble.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/trouble.trk $(DESTDIR)/usr/share/rars/tracks/trouble.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/tremblnt.trk /usr/share/rars/tracks/tremblnt.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/tremblnt.trk $(DESTDIR)/usr/share/rars/tracks/tremblnt.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/sepang.trk /usr/share/rars/tracks/sepang.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/sepang.trk $(DESTDIR)/usr/share/rars/tracks/sepang.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/season /usr/share/rars/tracks/season
#>+ 1
	$(INSTALL_DATA) $(srcdir)/season $(DESTDIR)/usr/share/rars/tracks/season
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/silverst.trk /usr/share/rars/tracks/silverst.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/silverst.trk $(DESTDIR)/usr/share/rars/tracks/silverst.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/spa.trk /usr/share/rars/tracks/spa.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/spa.trk $(DESTDIR)/usr/share/rars/tracks/spa.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/speed2.trk /usr/share/rars/tracks/speed2.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/speed2.trk $(DESTDIR)/usr/share/rars/tracks/speed2.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/stef2.trk /usr/share/rars/tracks/stef2.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/stef2.trk $(DESTDIR)/usr/share/rars/tracks/stef2.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/suzuka.trk /usr/share/rars/tracks/suzuka.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/suzuka.trk $(DESTDIR)/usr/share/rars/tracks/suzuka.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/timin.trk /usr/share/rars/tracks/timin.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/timin.trk $(DESTDIR)/usr/share/rars/tracks/timin.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/random.trk /usr/share/rars/tracks/random.trk
#>+ 1
	$(INSTALL_DATA) $(srcdir)/random.trk $(DESTDIR)/usr/share/rars/tracks/random.trk
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/t_eight.trx /usr/share/rars/tracks/t_eight.trx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/t_eight.trx $(DESTDIR)/usr/share/rars/tracks/t_eight.trx
#>- 	$(mkinstalldirs) /usr/share/rars/tracks/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/tracks/
#>- 	$(INSTALL_DATA) $(srcdir)/t_zero.trx /usr/share/rars/tracks/t_zero.trx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/t_zero.trx $(DESTDIR)/usr/share/rars/tracks/t_zero.trx

uninstall-local:
#>- 	-rm -f /usr/share/rars/tracks/aalborg.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/aalborg.trk
#>- 	-rm -f /usr/share/rars/tracks/adelaide.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/adelaide.trk
#>- 	-rm -f /usr/share/rars/tracks/albert.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/albert.trk
#>- 	-rm -f /usr/share/rars/tracks/albrtprk.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/albrtprk.trk
#>- 	-rm -f /usr/share/rars/tracks/anew.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/anew.trk
#>- 	-rm -f /usr/share/rars/tracks/austria.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/austria.trk
#>- 	-rm -f /usr/share/rars/tracks/barcelon.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/barcelon.trk
#>- 	-rm -f /usr/share/rars/tracks/brands.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/brands.trk
#>- 	-rm -f /usr/share/rars/tracks/brazil.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/brazil.trk
#>- 	-rm -f /usr/share/rars/tracks/buenos.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/buenos.trk
#>- 	-rm -f /usr/share/rars/tracks/clkwis.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/clkwis.trk
#>- 	-rm -f /usr/share/rars/tracks/cstlcomb.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/cstlcomb.trk
#>- 	-rm -f /usr/share/rars/tracks/doningtn.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/doningtn.trk
#>- 	-rm -f /usr/share/rars/tracks/zandvort.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/zandvort.trk
#>- 	-rm -f /usr/share/rars/tracks/dreiw.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/dreiw.trk
#>- 	-rm -f /usr/share/rars/tracks/elev2.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/elev2.trk
#>- 	-rm -f /usr/share/rars/tracks/estoril.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/estoril.trk
#>- 	-rm -f /usr/share/rars/tracks/figure8.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/figure8.trk
#>- 	-rm -f /usr/share/rars/tracks/fiorano.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/fiorano.trk
#>- 	-rm -f /usr/share/rars/tracks/fourmile.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/fourmile.trk
#>- 	-rm -f /usr/share/rars/tracks/hock.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/hock.trk
#>- 	-rm -f /usr/share/rars/tracks/hungary.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/hungary.trk
#>- 	-rm -f /usr/share/rars/tracks/kevin.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/kevin.trk
#>- 	-rm -f /usr/share/rars/tracks/imola.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/imola.trk
#>- 	-rm -f /usr/share/rars/tracks/indy500.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/indy500.trk
#>- 	-rm -f /usr/share/rars/tracks/indygp.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/indygp.trk
#>- 	-rm -f /usr/share/rars/tracks/jerez.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/jerez.trk
#>- 	-rm -f /usr/share/rars/tracks/kimla01.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/kimla01.trk
#>- 	-rm -f /usr/share/rars/tracks/kimla02.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/kimla02.trk
#>- 	-rm -f /usr/share/rars/tracks/kimla03.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/kimla03.trk
#>- 	-rm -f /usr/share/rars/tracks/kimla04.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/kimla04.trk
#>- 	-rm -f /usr/share/rars/tracks/kimla05.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/kimla05.trk
#>- 	-rm -f /usr/share/rars/tracks/longrand.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/longrand.trk
#>- 	-rm -f /usr/share/rars/tracks/loudon.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/loudon.trk
#>- 	-rm -f /usr/share/rars/tracks/magnycrs.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/magnycrs.trk
#>- 	-rm -f /usr/share/rars/tracks/michigan.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/michigan.trk
#>- 	-rm -f /usr/share/rars/tracks/midohio.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/midohio.trk
#>- 	-rm -f /usr/share/rars/tracks/mlwaukee.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/mlwaukee.trk
#>- 	-rm -f /usr/share/rars/tracks/monaco.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/monaco.trk
#>- 	-rm -f /usr/share/rars/tracks/montreal.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/montreal.trk
#>- 	-rm -f /usr/share/rars/tracks/nurnburg.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/nurnburg.trk
#>- 	-rm -f /usr/share/rars/tracks/phoenix.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/phoenix.trk
#>- 	-rm -f /usr/share/rars/tracks/oval2.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/oval2.trk
#>- 	-rm -f /usr/share/rars/tracks/monza-55.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/monza-55.trk
#>- 	-rm -f /usr/share/rars/tracks/monza-76.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/monza-76.trk
#>- 	-rm -f /usr/share/rars/tracks/mosport.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/mosport.trk
#>- 	-rm -f /usr/share/rars/tracks/nazareth.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/nazareth.trk
#>- 	-rm -f /usr/share/rars/tracks/per1.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/per1.trk
#>- 	-rm -f /usr/share/rars/tracks/pocono.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/pocono.trk
#>- 	-rm -f /usr/share/rars/tracks/ra.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/ra.trk
#>- 	-rm -f /usr/share/rars/tracks/ramdu.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/ramdu.trk
#>- 	-rm -f /usr/share/rars/tracks/rars.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/rars.trk
#>- 	-rm -f /usr/share/rars/tracks/s1.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/s1.trk
#>- 	-rm -f /usr/share/rars/tracks/silver97.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/silver97.trk
#>- 	-rm -f /usr/share/rars/tracks/wierd.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/wierd.trk
#>- 	-rm -f /usr/share/rars/tracks/watglen.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/watglen.trk
#>- 	-rm -f /usr/share/rars/tracks/v03.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/v03.trk
#>- 	-rm -f /usr/share/rars/tracks/v02.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/v02.trk
#>- 	-rm -f /usr/share/rars/tracks/s2.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/s2.trk
#>- 	-rm -f /usr/share/rars/tracks/v01.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/v01.trk
#>- 	-rm -f /usr/share/rars/tracks/trouble.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/trouble.trk
#>- 	-rm -f /usr/share/rars/tracks/tremblnt.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/tremblnt.trk
#>- 	-rm -f /usr/share/rars/tracks/sepang.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/sepang.trk
#>- 	-rm -f /usr/share/rars/tracks/season
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/season
#>- 	-rm -f /usr/share/rars/tracks/silverst.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/silverst.trk
#>- 	-rm -f /usr/share/rars/tracks/spa.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/spa.trk
#>- 	-rm -f /usr/share/rars/tracks/speed2.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/speed2.trk
#>- 	-rm -f /usr/share/rars/tracks/stef2.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/stef2.trk
#>- 	-rm -f /usr/share/rars/tracks/suzuka.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/suzuka.trk
#>- 	-rm -f /usr/share/rars/tracks/timin.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/timin.trk
#>- 	-rm -f /usr/share/rars/tracks/random.trk
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/random.trk
#>- 	-rm -f /usr/share/rars/tracks/t_eight.trx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/t_eight.trx
#>- 	-rm -f /usr/share/rars/tracks/t_zero.trx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/tracks/t_zero.trx

####### kdevelop will overwrite this part!!! (end)############
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 6
force-reedit:
		cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  rars/tracks/Makefile
	cd $(top_srcdir) && perl admin/am_edit rars/tracks/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 2
final-install:
	$(MAKE) install-am
#>+ 2
no-final:
	$(MAKE) all-am
#>+ 2
no-final-install:
	$(MAKE) install-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
