# KDE tags expanded automatically by am_edit - $Revision: 1.19 $ 
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



####### kdevelop will overwrite this part!!! (begin)##########

SHELL = /bin/bash

srcdir = .
top_srcdir = ../..

prefix = /usr/local/kde
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/share/info
mandir = ${prefix}/share/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/rars
pkglibdir = $(libdir)/rars
pkgincludedir = $(includedir)/rars
top_builddir = ../..

ACLOCAL = ${SHELL} /home/user/torcs/rars/admin/missing --run aclocal-1.11
AUTOCONF = ${SHELL} /home/user/torcs/rars/admin/missing --run autoconf
AUTOMAKE = ${SHELL} /home/user/torcs/rars/admin/missing --run automake-1.11
AUTOHEADER = ${SHELL} /home/user/torcs/rars/admin/missing --run autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = 
build_triplet = i686-pc-linux-gnu
host_alias = 
host_triplet = i686-pc-linux-gnu
target_alias = 
target_triplet = i686-pc-linux-gnu
AMTAR = ${SHELL} /home/user/torcs/rars/admin/missing --run tar
ARTSCCONFIG = 
AS = @AS@
AUTODIRS = 
AWK = gawk
CC = /usr/bin/gcc-4.1
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in
CPP = /usr/bin/gcc-4.1 -E
CXX = /usr/bin/g++-4.1
CXXCPP = /usr/bin/g++-4.1 -E
DCOPIDL = /usr/bin/dcopidl
DCOPIDL2CPP = /usr/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /usr/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/usr/include/kde
KDE_LDFLAGS = -L/usr/lib
KDE_MT_LDFLAGS = 
KDE_MT_LIBS = -lpthread
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = -R $(kde_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = /usr/share/apps/ksgmltools2/customization/kde-chunk.xsl
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBGEN = @LIBGEN@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = 
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = -lresolv
LIBSHADOW = @LIBSHADOW@
LIBSM = -lSM -lICE
LIBSOCKET =  -lresolv
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBUTIL = -lutil
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEPRINT = -lkdeprint
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkio
LIB_KFM = 
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lkio
LIB_QPE = 
LIB_QT = -lqt-mt  $(LIBPNG) -lXext $(LIB_X11) $(LIBSM) -lpthread
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LIB_XEXT = -lXext
LN_S = ln -s
MCOPIDL = 
MEINPROC = /usr/bin/meinproc
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CFLAGS = 
NOOPT_CXXFLAGS = 
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = rars
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTE_NORTTI = 
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = -I/usr/include/qt3
QT_LDFLAGS = 
RANLIB = ranlib
RC = @RC@
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  doc po rars
UIC = /usr/bin/uic -L $(kde_widgetdir) -nounload
UIC_TR = tr2i18n
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = 
USE_RTTI = 
USE_THREADS = 
VERSION = 0.90
WOVERLOADED_VIRTUAL = 
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS =  -lresolv
X_INCLUDES = -I.
X_LDFLAGS = -L/usr/lib
X_PRE_LIBS = 
all_includes = -I/usr/include/kde -I/usr/include/qt3 -I. 
all_libraries = -L/usr/lib 
am__include = include
am__quote = 
idldir = @idldir@
install_sh = ${SHELL} /home/user/torcs/rars/admin/install-sh
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /usr/include/kde
kde_libraries = /usr/lib
kde_libs_htmldir = /usr/share/doc/kde/HTML
kde_libs_prefix = /usr
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${libdir}/kde3
kde_qtver = 3
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_styledir = ${libdir}/kde3/plugins/styles
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
kde_widgetdir = ${libdir}/kde3/plugins/designer
micodir = @micodir@
qt_includes = /usr/include/qt3
qt_libraries = 
x_includes = .
x_libraries = /usr/lib

noinst_LIBRARIES = libgraphics.a

INCLUDES = $(all_includes)

#>- libgraphics_a_METASOURCES = AUTO

libgraphics_a_SOURCES = g_track_area.cpp g_track_bitmap.cpp g_geom.cpp g_tracked.cpp g_track3d.cpp kde_lowgr.cpp g_vmanag.cpp g_viewtl.cpp g_viewcl.cpp g_viewbd.cpp g_view3d.cpp g_view2d.cpp g_view.cpp g_rars_ini.cpp g_palett.cpp g_os.cpp g_opengl.cpp g_main.cpp g_lowgra.cpp g_draw.cpp g_divers.cpp g_bitmap.cpp 

EXTRA_DIST = g_bitmap.cpp g_bitmap.h g_define.h g_divers.cpp g_draw.cpp g_global.h g_lowgra.cpp g_main.cpp g_main.h g_opengl.cpp g_os.cpp g_palett.cpp g_rars_ini.cpp g_rars_ini.h g_view.cpp g_view.h g_view2d.cpp g_view3d.cpp g_viewbd.cpp g_viewcl.cpp g_viewtl.cpp g_vmanag.cpp kde_defi.h kde_lowgr.cpp g_track3d.cpp g_track3d.h g_tracked.cpp g_tracked.h g_geom.cpp g_geom.h g_track_bitmap.cpp g_opengl.h g_track_area.cpp 
subdir = rars/graphics
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(noinst_LIBRARIES)

libgraphics_a_AR = $(AR) cru
libgraphics_a_LIBADD =
am_libgraphics_a_OBJECTS = g_track_area.$(OBJEXT) \
	g_track_bitmap.$(OBJEXT) g_geom.$(OBJEXT) g_tracked.$(OBJEXT) \
	g_track3d.$(OBJEXT) kde_lowgr.$(OBJEXT) g_vmanag.$(OBJEXT) \
	g_viewtl.$(OBJEXT) g_viewcl.$(OBJEXT) g_viewbd.$(OBJEXT) \
	g_view3d.$(OBJEXT) g_view2d.$(OBJEXT) g_view.$(OBJEXT) \
	g_rars_ini.$(OBJEXT) g_palett.$(OBJEXT) g_os.$(OBJEXT) \
	g_opengl.$(OBJEXT) g_main.$(OBJEXT) g_lowgra.$(OBJEXT) \
	g_draw.$(OBJEXT) g_divers.$(OBJEXT) g_bitmap.$(OBJEXT)
#>- libgraphics_a_OBJECTS = $(am_libgraphics_a_OBJECTS)
#>+ 11
libgraphics_a_final_OBJECTS = libgraphics_a.all_cpp.o 
libgraphics_a_nofinal_OBJECTS = g_track_area.$(OBJEXT) \
	g_track_bitmap.$(OBJEXT) g_geom.$(OBJEXT) g_tracked.$(OBJEXT) \
	g_track3d.$(OBJEXT) kde_lowgr.$(OBJEXT) g_vmanag.$(OBJEXT) \
	g_viewtl.$(OBJEXT) g_viewcl.$(OBJEXT) g_viewbd.$(OBJEXT) \
	g_view3d.$(OBJEXT) g_view2d.$(OBJEXT) g_view.$(OBJEXT) \
	g_rars_ini.$(OBJEXT) g_palett.$(OBJEXT) g_os.$(OBJEXT) \
	g_opengl.$(OBJEXT) g_main.$(OBJEXT) g_lowgra.$(OBJEXT) \
	g_draw.$(OBJEXT) g_divers.$(OBJEXT) g_bitmap.$(OBJEXT)
libgraphics_a_OBJECTS = $(libgraphics_a_nofinal_OBJECTS)
#libgraphics_a_OBJECTS = $(libgraphics_a_final_OBJECTS)

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS =  -DQT_THREAD_SUPPORT  -D_REENTRANT
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/admin/depcomp
DEP_FILES = $(DEPDIR)/g_bitmap.Po $(DEPDIR)/g_divers.Po \
		$(DEPDIR)/g_draw.Po $(DEPDIR)/g_geom.Po \
		$(DEPDIR)/g_lowgra.Po $(DEPDIR)/g_main.Po \
		$(DEPDIR)/g_opengl.Po $(DEPDIR)/g_os.Po \
		$(DEPDIR)/g_palett.Po $(DEPDIR)/g_rars_ini.Po \
		$(DEPDIR)/g_track3d.Po $(DEPDIR)/g_track_area.Po \
		$(DEPDIR)/g_track_bitmap.Po $(DEPDIR)/g_tracked.Po \
		$(DEPDIR)/g_view.Po $(DEPDIR)/g_view2d.Po \
		$(DEPDIR)/g_view3d.Po $(DEPDIR)/g_viewbd.Po \
		$(DEPDIR)/g_viewcl.Po $(DEPDIR)/g_viewtl.Po \
		$(DEPDIR)/g_vmanag.Po $(DEPDIR)/kde_lowgr.Po
#>- CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
#>- $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 2
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) \
#>- $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
#>- $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 3
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
#>- $(AM_LDFLAGS) $(LDFLAGS) -o $@
#>+ 2
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXFLAGS = -O0 -g3 -Wall -I..
DIST_SOURCES = $(libgraphics_a_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(libgraphics_a_SOURCES)

#>- all: all-am
#>+ 1
all: docs-am  all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
#>- 	cd $(top_srcdir) && \
#>- $(AUTOMAKE) --gnu  rars/graphics/Makefile
#>+ 3
	cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  rars/graphics/Makefile
	cd $(top_srcdir) && perl admin/am_edit rars/graphics/Makefile.in
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	CONFIG_HEADERS= CONFIG_LINKS= \
	CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

AR = ar

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libgraphics.a: $(libgraphics_a_OBJECTS) $(libgraphics_a_DEPENDENCIES) 
	-rm -f libgraphics.a
	$(libgraphics_a_AR) libgraphics.a $(libgraphics_a_OBJECTS) $(libgraphics_a_LIBADD)
	$(RANLIB) libgraphics.a

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/g_bitmap.Po
include $(DEPDIR)/g_divers.Po
include $(DEPDIR)/g_draw.Po
include $(DEPDIR)/g_geom.Po
include $(DEPDIR)/g_lowgra.Po
include $(DEPDIR)/g_main.Po
include $(DEPDIR)/g_opengl.Po
include $(DEPDIR)/g_os.Po
include $(DEPDIR)/g_palett.Po
include $(DEPDIR)/g_rars_ini.Po
include $(DEPDIR)/g_track3d.Po
include $(DEPDIR)/g_track_area.Po
include $(DEPDIR)/g_track_bitmap.Po
include $(DEPDIR)/g_tracked.Po
include $(DEPDIR)/g_view.Po
include $(DEPDIR)/g_view2d.Po
include $(DEPDIR)/g_view3d.Po
include $(DEPDIR)/g_viewbd.Po
include $(DEPDIR)/g_viewcl.Po
include $(DEPDIR)/g_viewtl.Po
include $(DEPDIR)/g_vmanag.Po
include $(DEPDIR)/kde_lowgr.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

.cpp.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CXXDEPMODE) $(depcomp) \
	$(LTCXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CXXDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	done | \
	$(AWK) '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
	$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	done | \
	$(AWK) '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	|| etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	&& cd $(top_srcdir) \
	&& gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

#>- DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=libgraphics.a g_viewte.cpp vc_defin.h vc_lowgr.cpp 

DISTFILES= $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	if test -f $$file; then d=.; else d=$(srcdir); fi; \
	dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	$(mkinstalldirs) "$(distdir)/$$dir"; \
	fi; \
	if test -d $$d/$$file; then \
	cp -pR $$d/$$file $(distdir) \
	|| exit 1; \
	else \
	test -f $(distdir)/$$file \
	|| cp -p $$d/$$file $(distdir)/$$file \
	|| exit 1; \
	fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	`test -z '$(STRIP)' || \
	echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

#>- clean-am: clean-generic clean-libtool clean-noinstLIBRARIES \
#>- mostlyclean-am
#>+ 2
clean-am: clean-final  clean-generic clean-libtool clean-noinstLIBRARIES \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-noinstLIBRARIES distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	tags uninstall uninstall-am uninstall-info-am


####### kdevelop will overwrite this part!!! (end)############
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 6
force-reedit:
		cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  rars/graphics/Makefile
	cd $(top_srcdir) && perl admin/am_edit rars/graphics/Makefile.in


#>+ 11
libgraphics_a.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/g_track_area.cpp $(srcdir)/g_track_bitmap.cpp $(srcdir)/g_geom.cpp $(srcdir)/g_tracked.cpp $(srcdir)/g_track3d.cpp $(srcdir)/kde_lowgr.cpp $(srcdir)/g_vmanag.cpp $(srcdir)/g_viewtl.cpp $(srcdir)/g_viewcl.cpp $(srcdir)/g_viewbd.cpp $(srcdir)/g_view3d.cpp $(srcdir)/g_view2d.cpp $(srcdir)/g_view.cpp $(srcdir)/g_rars_ini.cpp $(srcdir)/g_palett.cpp $(srcdir)/g_os.cpp $(srcdir)/g_opengl.cpp $(srcdir)/g_main.cpp $(srcdir)/g_lowgra.cpp $(srcdir)/g_draw.cpp $(srcdir)/g_divers.cpp $(srcdir)/g_bitmap.cpp  
	@echo 'creating libgraphics_a.all_cpp.cpp ...'; \
	rm -f libgraphics_a.all_cpp.files libgraphics_a.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> libgraphics_a.all_cpp.final; \
	for file in g_track_area.cpp g_track_bitmap.cpp g_geom.cpp g_tracked.cpp g_track3d.cpp kde_lowgr.cpp g_vmanag.cpp g_viewtl.cpp g_viewcl.cpp g_viewbd.cpp g_view3d.cpp g_view2d.cpp g_view.cpp g_rars_ini.cpp g_palett.cpp g_os.cpp g_opengl.cpp g_main.cpp g_lowgra.cpp g_draw.cpp g_divers.cpp g_bitmap.cpp ; do \
	  echo "#include \"$$file\"" >> libgraphics_a.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> libgraphics_a.all_cpp.final; \
	done; \
	cat libgraphics_a.all_cpp.final libgraphics_a.all_cpp.files  > libgraphics_a.all_cpp.cpp; \
	rm -f libgraphics_a.all_cpp.final libgraphics_a.all_cpp.files

#>+ 3
clean-final:
	-rm -f libgraphics_a.all_cpp.cpp

#>+ 2
final:
	$(MAKE) libgraphics_a_OBJECTS="$(libgraphics_a_final_OBJECTS)" all-am
#>+ 2
final-install:
	$(MAKE) libgraphics_a_OBJECTS="$(libgraphics_a_final_OBJECTS)" install-am
#>+ 2
no-final:
	$(MAKE) libgraphics_a_OBJECTS="$(libgraphics_a_nofinal_OBJECTS)" all-am
#>+ 2
no-final-install:
	$(MAKE) libgraphics_a_OBJECTS="$(libgraphics_a_nofinal_OBJECTS)" install-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
