//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vc_rars.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RARS_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_DIALOG_MENU                 129
#define IDR_ACCELERATOR1                131
#define IDD_StartRace                   133
#define IDD_StartRaceBulle              134
#define IDB_BITMAP1                     136
#define IDD_INIT_CARS                   144
#define IDR_RARS_ACCELERATOR            147
#define IDD_TRACK_EDITOR                148
#define IDR_TRACK_MENU                  150
#define IDR_START                       151
#define IDR_TRACK_ACCELERATOR           152
#define IDD_TRACK_PROPERTY              153
#define IDD_TRACK_LOAD                  154
#define IDD_TRACK_SECTION               160
#define IDC_BITMAP_2D                   1003
#define IDC_BITMAP_CLASSIC              1004
#define IDC_BITMAP_BOARD                1006
#define IDC_TRACK_NAME                  1012
#define IDC_LAPS                        1013
#define IDC_SPIN1                       1015
#define IDC_SPIN2                       1016
#define IDC_OPTI_STYLE                  1017
#define IDC_QUALIF_LAPS                 1017
#define IDC_RES1                        1018
#define IDC_SPIN4                       1018
#define IDC_RES2                        1019
#define IDC_RANDOM                      1019
#define IDC_OPTI_NB                     1021
#define IDC_QUALIF_SESSIONS             1021
#define IDC_SPIN3                       1022
#define IDC_LIST_TRACK                  1023
#define IDC_QUALIF_CARS                 1023
#define IDC_ADD_TRACK                   1024
#define IDC_SPIN5                       1024
#define IDC_RES0                        1025
#define IDC_ADD_ALL_TRACK               1026
#define IDC_DEL_TRACK                   1027
#define IDC_OPTI_START                  1030
#define IDC_REPLAY                      1032
#define IDC_RADIO1                      1045
#define IDC_RADIO2                      1046
#define IDC_RADIO3                      1047
#define IDC_RADIO4                      1048
#define IDC_RADIO5                      1049
#define IDC_OPEN_GL                     1049
#define IDC_MOVIE                       1050
#define IDC_BUTTON_RANDOM               1051
#define IDC_LAST_RESULT                 1052
#define IDC_FOLLOW_CAR                  1053
#define IDC_DRIVER_SELECT_ALL           1054
#define IDC_DRIVER_REMOVE_ALL           1055
#define IDC_DRIVER_SELECT_ONE           1056
#define IDC_DRIVER_REMOVE_ONE           1057
#define IDC_DRIVER_AVAILABLE            1058
#define IDC_DRIVER_SELECTED             1059
#define IDC_SEGMENT_LIST                1060
#define IDC_SURFACE                     1060
#define IDC_DESCRIPTION                 1067
#define IDC_PROP_NAME                   1068
#define IDC_PROP_VALUE                  1069
#define IDC_CENTER_LIST                 1070
#define IDC_PROP_RESET                  1071
#define IDC_LEFT_LIST                   1072
#define IDC_PROP_SET                    1073
#define IDC_RIGHT_LIST                  1074
#define IDC_SECTION_LIST                1077
#define IDC_SECTION                     1078
#define IDC_CLIPBOARD                   1079
#define IDC_LIST_MESSAGE                1080
#define IDC_PROP_LIST                   1081
#define ID_SPEED_SLOW                   32771
#define ID_SPEED_MEDIUM                 32772
#define ID_SPEED_FAST                   32773
#define ID_CAR_PRV_CAR                  32775
#define ID_CAR_NEXT_CAR                 32776
#define ID_OPENGL_VIEW                  32777
#define ID_OPENGL_DISABLED              32779
#define ID_OPENGL_CLASSIC               32779
#define ID_VIEW_CLASSIC                 32779
#define ID_OPENGL_WINDOW                32780
#define ID_VIEW_OPENGL_WINDOW           32780
#define ID_OPENGL_FULLSCREEN            32781
#define ID_VIEW_OPENGL_FULLSCREEN       32781
#define ID_OPENGL_TELEMETRY             32782
#define ID_VIEW_TELEMETRY               32782
#define ID_OPENGL_ZOOM                  32783
#define ID_VIEW_ZOOM                    32783
#define ID_CAR_ANY_OVERTAKING           32784
#define ID_CAR_FOR_POSITION             32785
#define ID_CAR_MANUAL                   32786
#define ID_ZOOM_IN                      32787
#define ID_ZOOM_OUT                     32788
#define ID_SETTINGS_SAVE                32791
#define ID_SPEED_STOP                   32792
#define ID_SPEED_REWIND                 32793
#define ID_VIEW_TRAJECTORY              32794
#define ID_CAR_NOBODY                   32795
#define ID_MOVE_LEFT                    32796
#define ID_MOVE_UP                      32797
#define ID_MOVE_DOWN                    32798
#define ID_MOVE_RIGHT                   32799
#define ID_VIEW_DRIVERNAMES             32801
#define ID_FILE_LOAD                    32802
#define ID_TRACK_GEN3D                  32806
#define ID_TRACK_TORCS                  32807
#define ID_VIEW_TRACK2D                 32808
#define ID_VIEW_TRACK3DS                32809
#define ID_SEGMENT_NEW                  32810
#define ID_SEGMENT_DELETE               32812
#define ID_TRACK_PROPERTY               32813
#define ID_VIEW_TRACK_ONE_SEG           32814
#define ID_ROTATE_UP                    32815
#define ID_ROTATE_DOWN                  32816
#define ID_ROTATE_LEFT                  32817
#define ID_ROTATE_RIGHT                 32818
#define ID_ROTATE_RESET                 32819
#define ID_SEGMENT_PRV                  -32715
#define ID_SEGMENT_NXT                  -32714
#define ID_SECTION_NEW                  32823
#define ID_EDIT_PASTE_ALL               32824
#define ID_SPEED_PAUSE                  32825
#define ID_TRACK_AUTOCLOSURE            32826
#define ID_SEGMENT_INFO                 32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
