# KDE tags expanded automatically by am_edit - $Revision: 1.7 $ 
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



####### kdevelop will overwrite this part!!! (begin)##########

SHELL = /bin/bash

srcdir = .
top_srcdir = ../..

prefix = /usr/local/kde
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/share/info
mandir = ${prefix}/share/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/rars
pkglibdir = $(libdir)/rars
pkgincludedir = $(includedir)/rars
top_builddir = ../..

ACLOCAL = ${SHELL} /home/user/torcs/rars/admin/missing --run aclocal-1.11
AUTOCONF = ${SHELL} /home/user/torcs/rars/admin/missing --run autoconf
AUTOMAKE = ${SHELL} /home/user/torcs/rars/admin/missing --run automake-1.11
AUTOHEADER = ${SHELL} /home/user/torcs/rars/admin/missing --run autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = 
build_triplet = i686-pc-linux-gnu
host_alias = 
host_triplet = i686-pc-linux-gnu
target_alias = 
target_triplet = i686-pc-linux-gnu
AMTAR = ${SHELL} /home/user/torcs/rars/admin/missing --run tar
ARTSCCONFIG = 
AS = @AS@
AUTODIRS = 
AWK = gawk
CC = /usr/bin/gcc-4.1
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in
CPP = /usr/bin/gcc-4.1 -E
CXX = /usr/bin/g++-4.1
CXXCPP = /usr/bin/g++-4.1 -E
DCOPIDL = /usr/bin/dcopidl
DCOPIDL2CPP = /usr/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /usr/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/usr/include/kde
KDE_LDFLAGS = -L/usr/lib
KDE_MT_LDFLAGS = 
KDE_MT_LIBS = -lpthread
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = -R $(kde_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = /usr/share/apps/ksgmltools2/customization/kde-chunk.xsl
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBGEN = @LIBGEN@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = 
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = -lresolv
LIBSHADOW = @LIBSHADOW@
LIBSM = -lSM -lICE
LIBSOCKET =  -lresolv
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBUTIL = -lutil
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEPRINT = -lkdeprint
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkio
LIB_KFM = 
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lkio
LIB_QPE = 
LIB_QT = -lqt-mt  $(LIBPNG) -lXext $(LIB_X11) $(LIBSM) -lpthread
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LIB_XEXT = -lXext
LN_S = ln -s
MCOPIDL = 
MEINPROC = /usr/bin/meinproc
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CFLAGS = 
NOOPT_CXXFLAGS = 
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = rars
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTE_NORTTI = 
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = -I/usr/include/qt3
QT_LDFLAGS = 
RANLIB = ranlib
RC = @RC@
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  doc po rars
UIC = /usr/bin/uic -L $(kde_widgetdir) -nounload
UIC_TR = tr2i18n
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = 
USE_RTTI = 
USE_THREADS = 
VERSION = 0.90
WOVERLOADED_VIRTUAL = 
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS =  -lresolv
X_INCLUDES = -I.
X_LDFLAGS = -L/usr/lib
X_PRE_LIBS = 
all_includes = -I/usr/include/kde -I/usr/include/qt3 -I. 
all_libraries = -L/usr/lib 
am__include = include
am__quote = 
idldir = @idldir@
install_sh = ${SHELL} /home/user/torcs/rars/admin/install-sh
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /usr/include/kde
kde_libraries = /usr/lib
kde_libs_htmldir = /usr/share/doc/kde/HTML
kde_libs_prefix = /usr
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${libdir}/kde3
kde_qtver = 3
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_styledir = ${libdir}/kde3/plugins/styles
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
kde_widgetdir = ${libdir}/kde3/plugins/designer
micodir = @micodir@
qt_includes = /usr/include/qt3
qt_libraries = 
x_includes = .
x_libraries = /usr/lib

EXTRA_DIST = color.pl0 car_black_black.pcx car_blue_blue.pcx car_gray_gray.pcx car_gray_green.pcx car_green_green.pcx car_green_red.pcx car_lblue_blue.pcx car_lgreen_lred.pcx car_lred_lred.pcx car_orange_orange.pcx car_pink_pink.pcx car_red_black.pcx car_red_red.pcx car_red_yellow.pcx car_white_black.pcx car_white_red.pcx car_white_white.pcx car_yellow_black.pcx car_yellow_yellow.pcx font8x8.pcx grass8x8.pcx pitstop.tga red_brick.tga road.tga road2.tga sky.tga tex1.tga grass.tga 
subdir = rars/bitmap
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
DIST_SOURCES =
DIST_COMMON = Makefile.am Makefile.in
#>- all: all-am
#>+ 1
all: docs-am  all-am

.SUFFIXES:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
#>- 	cd $(top_srcdir) && \
#>- $(AUTOMAKE) --gnu  rars/bitmap/Makefile
#>+ 3
	cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  rars/bitmap/Makefile
	cd $(top_srcdir) && perl admin/am_edit rars/bitmap/Makefile.in
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	CONFIG_HEADERS= CONFIG_LINKS= \
	CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
uninstall-info-am:
tags: TAGS
TAGS:


#>- DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=index.htm 

DISTFILES= $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	if test -f $$file; then d=.; else d=$(srcdir); fi; \
	dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	$(mkinstalldirs) "$(distdir)/$$dir"; \
	fi; \
	if test -d $$d/$$file; then \
	cp -pR $$d/$$file $(distdir) \
	|| exit 1; \
	else \
	test -f $(distdir)/$$file \
	|| cp -p $$d/$$file $(distdir)/$$file \
	|| exit 1; \
	fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	`test -z '$(STRIP)' || \
	echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-generic distclean-libtool

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-data-local

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

uninstall-am: uninstall-info-am uninstall-local

.PHONY: all all-am check check-am clean clean-generic clean-libtool \
	distclean distclean-generic distclean-libtool distdir dvi \
	dvi-am info info-am install install-am install-data \
	install-data-am install-data-local install-exec install-exec-am \
	install-info install-info-am install-man install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic \
	mostlyclean-libtool uninstall uninstall-am uninstall-info-am \
	uninstall-local


install-data-local:
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/color.pl0 /usr/share/rars/bitmap/color.pl0
#>+ 1
	$(INSTALL_DATA) $(srcdir)/color.pl0 $(DESTDIR)/usr/share/rars/bitmap/color.pl0
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_black_black.pcx /usr/share/rars/bitmap/car_black_black.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_black_black.pcx $(DESTDIR)/usr/share/rars/bitmap/car_black_black.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_blue_blue.pcx /usr/share/rars/bitmap/car_blue_blue.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_blue_blue.pcx $(DESTDIR)/usr/share/rars/bitmap/car_blue_blue.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_gray_gray.pcx /usr/share/rars/bitmap/car_gray_gray.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_gray_gray.pcx $(DESTDIR)/usr/share/rars/bitmap/car_gray_gray.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_gray_green.pcx /usr/share/rars/bitmap/car_gray_green.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_gray_green.pcx $(DESTDIR)/usr/share/rars/bitmap/car_gray_green.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_green_green.pcx /usr/share/rars/bitmap/car_green_green.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_green_green.pcx $(DESTDIR)/usr/share/rars/bitmap/car_green_green.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_green_red.pcx /usr/share/rars/bitmap/car_green_red.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_green_red.pcx $(DESTDIR)/usr/share/rars/bitmap/car_green_red.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_lblue_blue.pcx /usr/share/rars/bitmap/car_lblue_blue.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_lblue_blue.pcx $(DESTDIR)/usr/share/rars/bitmap/car_lblue_blue.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_lgreen_lred.pcx /usr/share/rars/bitmap/car_lgreen_lred.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_lgreen_lred.pcx $(DESTDIR)/usr/share/rars/bitmap/car_lgreen_lred.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_lred_lred.pcx /usr/share/rars/bitmap/car_lred_lred.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_lred_lred.pcx $(DESTDIR)/usr/share/rars/bitmap/car_lred_lred.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_orange_orange.pcx /usr/share/rars/bitmap/car_orange_orange.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_orange_orange.pcx $(DESTDIR)/usr/share/rars/bitmap/car_orange_orange.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_pink_pink.pcx /usr/share/rars/bitmap/car_pink_pink.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_pink_pink.pcx $(DESTDIR)/usr/share/rars/bitmap/car_pink_pink.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_red_black.pcx /usr/share/rars/bitmap/car_red_black.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_red_black.pcx $(DESTDIR)/usr/share/rars/bitmap/car_red_black.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_red_red.pcx /usr/share/rars/bitmap/car_red_red.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_red_red.pcx $(DESTDIR)/usr/share/rars/bitmap/car_red_red.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_red_yellow.pcx /usr/share/rars/bitmap/car_red_yellow.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_red_yellow.pcx $(DESTDIR)/usr/share/rars/bitmap/car_red_yellow.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_white_black.pcx /usr/share/rars/bitmap/car_white_black.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_white_black.pcx $(DESTDIR)/usr/share/rars/bitmap/car_white_black.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_white_red.pcx /usr/share/rars/bitmap/car_white_red.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_white_red.pcx $(DESTDIR)/usr/share/rars/bitmap/car_white_red.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_white_white.pcx /usr/share/rars/bitmap/car_white_white.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_white_white.pcx $(DESTDIR)/usr/share/rars/bitmap/car_white_white.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_yellow_black.pcx /usr/share/rars/bitmap/car_yellow_black.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_yellow_black.pcx $(DESTDIR)/usr/share/rars/bitmap/car_yellow_black.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/car_yellow_yellow.pcx /usr/share/rars/bitmap/car_yellow_yellow.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/car_yellow_yellow.pcx $(DESTDIR)/usr/share/rars/bitmap/car_yellow_yellow.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/font8x8.pcx /usr/share/rars/bitmap/font8x8.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/font8x8.pcx $(DESTDIR)/usr/share/rars/bitmap/font8x8.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/grass8x8.pcx /usr/share/rars/bitmap/grass8x8.pcx
#>+ 1
	$(INSTALL_DATA) $(srcdir)/grass8x8.pcx $(DESTDIR)/usr/share/rars/bitmap/grass8x8.pcx
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/pitstop.tga /usr/share/rars/bitmap/pitstop.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/pitstop.tga $(DESTDIR)/usr/share/rars/bitmap/pitstop.tga
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/red_brick.tga /usr/share/rars/bitmap/red_brick.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/red_brick.tga $(DESTDIR)/usr/share/rars/bitmap/red_brick.tga
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/road.tga /usr/share/rars/bitmap/road.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/road.tga $(DESTDIR)/usr/share/rars/bitmap/road.tga
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/road2.tga /usr/share/rars/bitmap/road2.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/road2.tga $(DESTDIR)/usr/share/rars/bitmap/road2.tga
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/sky.tga /usr/share/rars/bitmap/sky.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/sky.tga $(DESTDIR)/usr/share/rars/bitmap/sky.tga
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/tex1.tga /usr/share/rars/bitmap/tex1.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/tex1.tga $(DESTDIR)/usr/share/rars/bitmap/tex1.tga
#>- 	$(mkinstalldirs) /usr/share/rars/bitmap/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)/usr/share/rars/bitmap/
#>- 	$(INSTALL_DATA) $(srcdir)/grass.tga /usr/share/rars/bitmap/grass.tga
#>+ 1
	$(INSTALL_DATA) $(srcdir)/grass.tga $(DESTDIR)/usr/share/rars/bitmap/grass.tga

uninstall-local:
#>- 	-rm -f /usr/share/rars/bitmap/color.pl0
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/color.pl0
#>- 	-rm -f /usr/share/rars/bitmap/car_black_black.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_black_black.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_blue_blue.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_blue_blue.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_gray_gray.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_gray_gray.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_gray_green.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_gray_green.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_green_green.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_green_green.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_green_red.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_green_red.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_lblue_blue.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_lblue_blue.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_lgreen_lred.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_lgreen_lred.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_lred_lred.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_lred_lred.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_orange_orange.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_orange_orange.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_pink_pink.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_pink_pink.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_red_black.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_red_black.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_red_red.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_red_red.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_red_yellow.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_red_yellow.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_white_black.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_white_black.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_white_red.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_white_red.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_white_white.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_white_white.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_yellow_black.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_yellow_black.pcx
#>- 	-rm -f /usr/share/rars/bitmap/car_yellow_yellow.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/car_yellow_yellow.pcx
#>- 	-rm -f /usr/share/rars/bitmap/font8x8.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/font8x8.pcx
#>- 	-rm -f /usr/share/rars/bitmap/grass8x8.pcx
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/grass8x8.pcx
#>- 	-rm -f /usr/share/rars/bitmap/pitstop.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/pitstop.tga
#>- 	-rm -f /usr/share/rars/bitmap/red_brick.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/red_brick.tga
#>- 	-rm -f /usr/share/rars/bitmap/road.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/road.tga
#>- 	-rm -f /usr/share/rars/bitmap/road2.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/road2.tga
#>- 	-rm -f /usr/share/rars/bitmap/sky.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/sky.tga
#>- 	-rm -f /usr/share/rars/bitmap/tex1.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/tex1.tga
#>- 	-rm -f /usr/share/rars/bitmap/grass.tga
#>+ 1
	-rm -f $(DESTDIR)/usr/share/rars/bitmap/grass.tga

####### kdevelop will overwrite this part!!! (end)############
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 6
force-reedit:
		cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  rars/bitmap/Makefile
	cd $(top_srcdir) && perl admin/am_edit rars/bitmap/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 2
final-install:
	$(MAKE) install-am
#>+ 2
no-final:
	$(MAKE) all-am
#>+ 2
no-final-install:
	$(MAKE) install-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
